/* 1994/02/06 Hiroyuki Ogasawara (COR.) */

#include	"opexec.h"
#include	"extern.h"

T_OPTBL	opt[]= {
	{ 0x00,	l2B, tLD,	f_lii,	"LII"	},
	{ 0x01,	l2B, tLD,	f_lij,	"LIJ"	},
	{ 0x02,	l2B, tLD,	f_lia,	"LIA"	},
	{ 0x03,	l2B, tLD,	f_lib,	"LIB"	},
	{ 0x04,	l1B, tLDX,	f_ix,	"IX"	},
	{ 0x05,	l1B, tLDX,	f_dx,	"DX"	},
	{ 0x06,	l1B, tLDX,	f_iy,	"IY"	},
	{ 0x07,	l1B, tLDX,	f_dy,	"DY"	},

	{ 0x08,	l1B, tMV,	f_mvw,	"MVW"	},
	{ 0x09,	l1B, tMV,	f_exw,	"EXW"	},
	{ 0x0a,	l1B, tMV,	f_mvb,	"MVB"	},
	{ 0x0b,	l1B, tMV,	f_exb,	"EXB"	},
	{ 0x0c,	l1B, tMV,	f_adn,	"ADN"	},
	{ 0x0d,	l1B, tMV,	f_sbn,	"SBN"	},
	{ 0x0e,	l1B, tMV,	f_adw,	"ADW"	},
	{ 0x0f,	l1B, tMV,	f_sbw,	"SBW"	},

	{ 0x10,	l3B, tLD,	f_lidp,	"LIDP"	},
	{ 0x11,	l2B, tLD,	f_lidl,	"LIDL"	},
	{ 0x12,	l2B, tLD,	f_lip,	"LIP"	},
	{ 0x13,	l2B, tLD,	f_liq,	"LIQ"	},
	{ 0x14,	l1B, tADD,	f_adb,	"ADB"	},
	{ 0x15,	l1B, tADD,	f_sbb,	"SBB"	},
	{ 0x16,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x17,	l1B, tERR,	f_err,	"ERR"	},

	{ 0x18,	l1B, tMV,	f_mvwd,	"MVWD"	},
	{ 0x19,	l1B, tMV,	f_exwd,	"EXWD"	},
	{ 0x1a,	l1B, tMV,	f_mvbd,	"MVBD"	},
	{ 0x1b,	l1B, tMV,	f_exbd,	"EXBD"	},
	{ 0x1c,	l1B, tMV,	f_srw,	"SRW"	},
	{ 0x1d,	l1B, tMV,	f_slw,	"SLW"	},
	{ 0x1e,	l1B, tMV,	f_film,	"FILM"	},
	{ 0x1f,	l1B, tMV,	f_fild,	"FILD"	},

	{ 0x20,	l1B, tLD,	f_ldp,	"LDP"	},
	{ 0x21,	l1B, tLD,	f_ldq,	"LDQ"	},
	{ 0x22,	l1B, tLD,	f_ldr,	"LDR"	},
	{ 0x23,	l1B, tLD,	f_clra,	"CLRA"	},
	{ 0x24,	l1B, tLDX,	f_ixl,	"IXL"	},
	{ 0x25,	l1B, tLDX,	f_dxl,	"DXL"	},
	{ 0x26,	l1B, tLDX,	f_iys,	"IYS"	},
	{ 0x27,	l1B, tLDX,	f_dys,	"DYS"	},

	{ 0x28,	l2B, tJR,	f_jrnzp,"JRNZP"	},
	{ 0x29,	l2B, tJR,	f_jrnzm,"JRNZM"	},
	{ 0x2a,	l2B, tJR,	f_jrncp,"JRNCP"	},
	{ 0x2b,	l2B, tJR,	f_jrncm,"JRNCM"	},
	{ 0x2c,	l2B, tJR,	f_jrp,	"JRP"	},
	{ 0x2d,	l2B, tJR,	f_jrm,	"JRM"	},
	{ 0x2e,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x2f,	l2B, tST,	f_loop,	"LOOP"	},

	{ 0x30,	l1B, tLD,	f_stp,	"STP"	},
	{ 0x31,	l1B, tLD,	f_stq,	"STQ"	},
	{ 0x32,	l1B, tLD,	f_str,	"STR"	},
	{ 0x33,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x34,	l1B, tST,	f_push,	"PUSH"	},
	{ 0x35,	l1B, tMV,	f_data,	"DATA"	},
	{ 0x36,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x37,	l1B, tST,	f_ret,	"RET"	},

	{ 0x38,	l2B, tJR,	f_jrzp,	"JRZP"	},
	{ 0x39,	l2B, tJR,	f_jrzm,	"JRZM"	},
	{ 0x3a,	l2B, tJR,	f_jrcp,	"JRCP"	},
	{ 0x3b,	l2B, tJR,	f_jrcm,	"JRCM"	},
	{ 0x3c,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x3d,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x3e,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x3f,	l1B, tERR,	f_err,	"ERR"	},

	{ 0x40,	l1B, tINC,	f_inci,	"INCI"	},
	{ 0x41,	l1B, tDEC,	f_deci,	"DECI"	},
	{ 0x42,	l1B, tINC,	f_inca,	"INCA"	},
	{ 0x43,	l1B, tDEC,	f_deca,	"DECA"	},
	{ 0x44,	l1B, tADD,	f_adm,	"ADM"	},
	{ 0x45,	l1B, tADD,	f_sbm,	"SBM"	},
	{ 0x46,	l1B, tAND,	f_anma,	"ANMA"	},
	{ 0x47,	l1B, tAND,	f_orma,	"ORMA"	},

	{ 0x48,	l1B, tINC,	f_inck,	"INCK"	},
	{ 0x49,	l1B, tDEC,	f_deck,	"DECK"	},
	{ 0x4a,	l1B, tINC,	f_incm,	"INCM"	},
	{ 0x4b,	l1B, tDEC,	f_decm,	"DECM"	},
	{ 0x4c,	l1B, tPORT,	f_ina,	"INA"	},
	{ 0x4d,	l1B, tNOP,	f_nop,	"NOP"	},
	{ 0x4e,	l2B, tNOP,	f_wait,	"WAIT"	},
	{ 0x4f,	l1B, tMV,	f_ipxl,	"IPXL"	},

	{ 0x50,	l1B, tINC,	f_incp,	"INCP"	},
	{ 0x51,	l1B, tDEC,	f_decp,	"DECP"	},
	{ 0x52,	l1B, tLD,	f_std,	"STD"	},
	{ 0x53,	l1B, tLD,	f_mvdm,	"MVDM"	},
	{ 0x54,	l1B, tLD,	f_readm,"READM"	},
	{ 0x55,	l1B, tLD,	f_mvmd,	"MVMD"	},
	{ 0x56,	l1B, tLD,	f_read,	"READ"	},
	{ 0x57,	l1B, tLD,	f_ldd,	"LDD"	},

	{ 0x58,	l1B, tSFT,	f_swp,	"SWP"	},
	{ 0x59,	l1B, tLD,	f_ldm,	"LDM"	},
	{ 0x5a,	l1B, tSFT,	f_sl,	"SL"	},
	{ 0x5b,	l1B, tST,	f_pop,	"POP"	},
	{ 0x5c,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x5d,	l1B, tPORT,	f_outa,	"OUTA"	},
	{ 0x5e,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x5f,	l1B, tPORT,	f_outf,	"OUTF"	},

	{ 0x60,	l2B, tAND,	f_anim,	"ANIM"	},
	{ 0x61,	l2B, tAND,	f_orim,	"ORIM"	},
	{ 0x62,	l2B, tTS,	f_tsim,	"TSIM"	},
	{ 0x63,	l2B, tCP,	f_cpim,	"CPIM"	},
	{ 0x64,	l2B, tAND,	f_ania,	"ANIA"	},
	{ 0x65,	l2B, tAND,	f_oria,	"ORIA"	},
	{ 0x66,	l2B, tTS,	f_tsia,	"TSIA"	},
	{ 0x67,	l2B, tCP,	f_cpia,	"CPIA"	},

	{ 0x68,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x69,	lnB, tCASE,	f_case,	"CASE"	},
	{ 0x6a,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x6b,	l2B, tAND,	f_test,	"TEST"	},
	{ 0x6c,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x6d,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x6e,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x6f,	l1B, tMV,	f_ipxh,	"IPXH"	},

	{ 0x70,	l2B, tADD,	f_adim,	"ADIM"	},
	{ 0x71,	l2B, tADD,	f_sbim,	"SBIM"	},
	{ 0x72,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x73,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x74,	l2B, tADD,	f_adia,	"ADIA"	},
	{ 0x75,	l2B, tADD,	f_sbia,	"SBIA"	},
	{ 0x76,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x77,	l2B, tFLG,	f_rz,	"RZ"	},

	{ 0x78,	l3B, tST,	f_call,	"CALL"	},
	{ 0x79,	l3B, tJP,	f_jp,	"JP"	},
	{ 0x7a,	l4B, tST,	f_set,	"SET"	},
	{ 0x7b,	l1B, tERR,	f_err,	"ERR"	},
	{ 0x7c,	l3B, tJP,	f_jpnz,	"JPNZ"	},
	{ 0x7d,	l3B, tJP,	f_jpnc,	"JPNC"	},
	{ 0x7e,	l3B, tJP,	f_jpz,	"JPZ"	},
	{ 0x7f,	l3B, tJP,	f_jpc,	"JPC"	},

	{ 0x80,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x81,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x82,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x83,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x84,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x85,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x86,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x87,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x88,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x89,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x8a,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x8b,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x8c,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x8d,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x8e,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x8f,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x90,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x91,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x92,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x93,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x94,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x95,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x96,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x97,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x98,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x99,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x9a,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x9b,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x9c,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x9d,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x9e,	l1B, tLP,	f_lp,	"LP"	},
	{ 0x9f,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa0,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa1,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa2,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa3,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa4,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa5,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa6,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa7,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa8,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xa9,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xaa,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xab,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xac,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xad,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xae,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xaf,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb0,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb1,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb2,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb3,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb4,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb5,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb6,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb7,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb8,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xb9,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xba,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xbb,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xbc,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xbd,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xbe,	l1B, tLP,	f_lp,	"LP"	},
	{ 0xbf,	l1B, tLP,	f_lp,	"LP"	},

	{ 0xc0,	l1B, tINC,	f_incj,	"INCJ"	},
	{ 0xc1,	l1B, tDEC,	f_decj,	"DECJ"	},
	{ 0xc2,	l1B, tINC,	f_incb,	"INCB"	},
	{ 0xc3,	l1B, tDEC,	f_decb,	"DECB"	},
	{ 0xc4,	l1B, tADD,	f_adcm,	"ADCM"	},
	{ 0xc5,	l1B, tADD,	f_sbcm,	"SBCM"	},
	{ 0xc6,	l1B, tTS,	f_tsma,	"TSMA"	},
	{ 0xc7,	l1B, tCP,	f_cpma,	"CPMA"	},

	{ 0xc8,	l1B, tINC,	f_incl,	"INCL"	},
	{ 0xc9,	l1B, tDEC,	f_decl,	"DECL"	},
	{ 0xca,	l1B, tINC,	f_incn,	"INCN"	},
	{ 0xcb,	l1B, tDEC,	f_decn,	"DECN"	},
	{ 0xcc,	l1B, tPORT,	f_inb,	"INB"	},
	{ 0xcd,	l1B, tERR,	f_err,	"ERR"	},
	{ 0xce,	l1B, tNOP,	f_nopt,	"NOPT"	},
	{ 0xcf,	l1B, tERR,	f_err,	"ERR"	},

	{ 0xd0,	l1B, tFLG,	f_sc,	"SC"	},
	{ 0xd1,	l1B, tFLG,	f_rc,	"RC"	},
	{ 0xd2,	l1B, tSFT,	f_sr,	"SR"	},
	{ 0xd3,	l1B, tERR,	f_write,"WRITE"	},
	{ 0xd4,	l2B, tAND,	f_anid,	"ANID"	},
	{ 0xd5,	l2B, tAND,	f_orid,	"ORID"	},
	{ 0xd6,	l2B, tTS,	f_tsid,	"TSID"	},
	{ 0xd7,	l2B, tCP,	f_cpid,	"SZ"	},

	{ 0xd8,	l1B, tST,	f_reave,"REAVE"	},
	{ 0xd9,	l1B, tERR,	f_err,	"ERR"	},
	{ 0xda,	l1B, tEX,	f_exab,	"EXAB"	},
	{ 0xdb,	l1B, tEX,	f_exam,	"EXAM"	},
	{ 0xdc,	l1B, tERR,	f_err,	"ERR"	},
	{ 0xdd,	l1B, tPORT,	f_outb,	"OUTB"	},
	{ 0xde,	l1B, tERR,	f_err,	"ERR"	},
	{ 0xdf,	l1B, tPORT,	f_outc,	"OUTC"	},

	{ 0xe0,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xe1,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xe2,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xe3,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xe4,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xe5,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xe6,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xe7,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xe8,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xe9,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xea,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xeb,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xec,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xed,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xee,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xef,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf0,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf1,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf2,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf3,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf4,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf5,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf6,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf7,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf8,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xf9,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xfa,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xfb,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xfc,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xfd,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xfe,	l2B, tCAL,	f_cal,	"CAL"	},
	{ 0xff,	l2B, tCAL,	f_cal,	"CAL"	},
};


